services:
  app:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "5175:5175"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://5.129.202.183:8080/api
      - VITE_API_URL_BASE=http://5.129.202.183:8080:8080
    env_file:
      - .env
    command: npm run dev