name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Stop and remove existing container
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose down || true
          docker rm -f my-app || true
          docker rmi -f my-vite-app:prod || true

      - name: Build Docker image
        run: |
          cd $GITHUB_WORKSPACE
          docker build -t my-vite-app:prod .

      - name: Deploy new container
        run: |
          cd $GITHUB_WORKSPACE
          docker-compose up -d
